// <auto-generated />
namespace MultipleDbContext001.Migrations.Configuration1
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Conf1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Conf1));
        
        string IMigrationMetadata.Id
        {
            get { return "201712102120306_Conf1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
